# Generated by Django 4.1.4 on 2022-12-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_slug_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.CharField(default='0000', max_length=255),
            preserve_default=False,
        ),
    ]
