# Generated by Django 4.1.4 on 2022-12-20 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_add_zip_to_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='given_name',
        ),
    ]
